name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Unit test
        run: npm test
      - name: Lint code
        run: npm lint
  coverage:
    needs: [ test ]

    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATEKEY }}
        with:
          coverageCommand: npm test -- --coverage --coverageProvider=v8



